# Generated by Django 3.0.3 on 2020-08-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='thumbnill',
            new_name='thumbnil',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='thumbnill',
        ),
        migrations.AddField(
            model_name='projects',
            name='thumbnil',
            field=models.ImageField(blank=True, default='10th logo.jpg', null=True, upload_to='images'),
        ),
    ]
