# Generated by Django 3.0.3 on 2020-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0004_auto_20200815_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='pdf',
        ),
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
