# Generated by Django 3.0.3 on 2020-08-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0005_auto_20200815_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='url',
            new_name='link',
        ),
    ]
